# Generated by Django 4.1 on 2022-08-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0002_rename_cntactno_jobseeker_contactno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('firmname', models.CharField(max_length=100)),
                ('firmwork', models.TextField()),
                ('firmaddress', models.TextField()),
                ('cpname', models.CharField(max_length=50)),
                ('cpcontactno', models.CharField(max_length=15)),
                ('cpemailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adharno', models.CharField(max_length=12)),
                ('panno', models.CharField(max_length=10)),
                ('gstno', models.CharField(max_length=15)),
                ('regdat', models.CharField(max_length=20)),
            ],
        ),
    ]
